services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: storeit
      POSTGRES_PASSWORD: storeit
      POSTGRES_DB: storeit
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U storeit"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
