type: object
properties:
  name:
    type: string
  type:
    type: string
    enum:
      - pick
      - movement
  description:
    type: string
  unitId:
    type: string
    format: uuid
  assignedTo:
    type: string
    format: uuid
  items:
    type: array
    items:
      type: object
      properties:
        instanceId:
          type: string
          format: uuid
        targetCellId:
          type: string
          format: uuid
      required:
        - instanceId
required:
  - name
  - type
  - unitId
  - assignedTo
  - items
