allOf:
  - $ref: TaskBase.yaml
  - type: object
    properties:
      instances:
        type: array
        items:
          type: object
          properties:
            id:
              type: string
              format: uuid
              readOnly: true
            instance:
              $ref: ../../instances/models/InstanceFull.yaml
            sourceCell:
              $ref: ../../cells-groups/models/CellForInstance.yaml
            targetCell:
              nullable: true
              $ref: ../../cells-groups/models/CellForInstance.yaml
          required:
            - sourceCell
            - targetCell
            - instance
            - id
    required:
      - instances
