type: object
properties:
  id:
    type: string
    readOnly: true
    format: uuid
  name:
    type: string
  description:
    type: string
    nullable: true
  type:
    type: string
    enum:
      - pickment
      - movement
  status:
    type: string
    enum:
      - pending
      - in_progress
      - ready
      - completed
      - cancelled
  createdAt:
    type: string
    format: date-time
  unit:
    type: object
    $ref: ../../units/models/Unit.yaml
  assignedTo:
    $ref: ../../employees/models/EmployeeOptional.yaml
  assignedAt:
    type: string
    format: date-time
    nullable: true
  completedAt:
    type: string
    format: date-time
    nullable: true
required:
  - id
  - status
  - unit
  - name
  - type
  - createdAt
  - description
  - assignedTo
  - assignedAt
  - completedAt
