openapi: 3.0.3
info:
  title: storeit — backend
  contact:
    email: evgeny@evseevs.ru
  version: 0.0.1
  license:
    name: PRIVATE
    url: https://store-it.ru
servers:
  - url: http://localhost:8080/
security:
  - apiToken: []
  - cookie: []
components:
  securitySchemes:
    apiToken:
      description: API key authentication
      type: apiKey
      name: X-Api-Key
      in: header
    cookie:
      type: apiKey
      in: cookie
      name: storeit_session
tags: []
paths:
  /orgs:
    $ref: paths/orgs/orgs.yaml
  /orgs/{id}:
    $ref: paths/orgs/orgs_{id}.yaml

  /units:
    $ref: paths/units/units.yaml
  /units/{id}:
    $ref: paths/units/units_{id}.yaml

  /storage-groups:
    $ref: paths/storage-groups/storage-groups.yaml
  /storage-groups/{id}:
    $ref: paths/storage-groups/storage-groups_{id}.yaml

  /cells-groups:
    $ref: paths/cells-groups/cells-groups.yaml

  /cells-groups/{groupId}:
    $ref: paths/cells-groups/cells-groups_{id}.yaml

  /cells-groups/{groupId}/cells:
    $ref: paths/cells-groups/cells-groups_{id}_cells.yaml

  /cells-groups/{groupId}/cells/{cellId}:
    $ref: paths/cells-groups/cells-groups_{id}_cells_{cellId}.yaml

  /items:
    $ref: paths/items/items.yaml

  /items/{id}/variants:
    $ref: paths/items/items_{id}_variants.yaml

  /items/{id}/variants/{variantId}:
    $ref: paths/items/items_{id}_variants_{variantId}.yaml

  /items/{id}:
    $ref: paths/items/items_{id}.yaml

  /instances:
    $ref: paths/instances/instances.yaml

  /items/{itemId}/instances:
    $ref: paths/instances/items_{id}_instances.yaml

  /instances/{instanceId}:
    $ref: paths/instances/instances_{instanceId}.yaml

  /api-tokens:
    $ref: paths/api-tokens/api-tokens.yaml

  /api-tokens/{id}:
    $ref: paths/api-tokens/api-tokens_{id}.yaml

  /auth/oauth2/yandex:
    $ref: paths/auth/yandex.yaml

  /auth/logout:
    $ref: paths/auth/logout.yaml

  /me:
    $ref: paths/users/me.yaml

  # /tasks:
  #   $ref: paths/tasks/tasks.yaml

  # /tasks/{id}:
  #   $ref: paths/tasks/tasks_{id}.yaml

  # /tasks/{id}/pick-item:
  #   $ref: paths/tasks/tasks_{id}_pick-item.yaml
  # /tasks/{id}/put-item:
  #   $ref: paths/tasks/tasks_{id}_put-item.yaml

  # /tasks/{id}/awaiting:
  #   $ref: paths/tasks/tasks_{id}_awaiting.yaml

  # /tasks/{id}/done:
  #   $ref: paths/tasks/tasks_{id}_done.yaml

  # /tasks/{id}/cancel:
  #   $ref: paths/tasks/tasks_{id}_cancel.yaml

  /employees:
    $ref: paths/employees/employees.yaml
  /employees/{id}:
    $ref: paths/employees/employees_{id}.yaml
  /employees/invite:
    $ref: paths/employees/employees_invite.yaml
  /app/roles:
    $ref: paths/employees/roles.yaml

  /audit-logs:
    $ref: paths/audit-logs/audit-logs.yaml
