parameters:
  - name: id
    in: path
    required: true
    schema:
      type: string
      format: uuid
post:
  tags:
    - tasks
  summary: Put an item in target cell
  operationId: putItemInTargetCell
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/tasks/PutItemInCellRequest.yaml
  responses:
    "201":
      description: Successful operation
    "401":
      $ref: ../../components/responses/default-unauthorized.yaml
    "403":
      $ref: ../../components/responses/default-forbidden.yaml
    default:
      $ref: ../../components/responses/default-error.yaml
    "400":
      $ref: ../../components/responses/default-bad-request.yaml
