get:
  tags:
    - tasks
  summary: Get all tasks for organization
  operationId: getTasks
  responses:
    "200":
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/tasks/GetTasksResponse.yaml
    "401":
      $ref: ../../components/responses/default-unauthorized.yaml
    "403":
      $ref: ../../components/responses/default-forbidden.yaml
    default:
      $ref: ../../components/responses/default-error.yaml
    "404":
      $ref: ../../components/responses/default-not-found.yaml
post:
  tags:
    - tasks
  summary: Create a task
  operationId: createTask
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/tasks/CreateTaskRequest.yaml
  responses:
    "200":
      description: Successful operation
      content:
        application/json:
          schema:
            $ref: ../../components/schemas/tasks/CreateTaskResponse.yaml
    "401":
      $ref: ../../components/responses/default-unauthorized.yaml
    "403":
      $ref: ../../components/responses/default-forbidden.yaml
    default:
      $ref: ../../components/responses/default-error.yaml
    "400":
      $ref: ../../components/responses/default-bad-request.yaml
