parameters:
  - name: id
    in: path
    required: true
    schema:
      type: string
      format: uuid
post:
  tags:
    - tasks
  summary: Pick an item from cell
  operationId: pickItemFromCell
  requestBody:
    required: true
    content:
      application/json:
        schema:
          $ref: ../../components/schemas/tasks/PickItemFromCellRequest.yaml
  responses:
    "201":
      description: Successful operation
    "401":
      $ref: ../../components/responses/default-unauthorized.yaml
    "403":
      $ref: ../../components/responses/default-forbidden.yaml
    default:
      $ref: ../../components/responses/default-error.yaml
