parameters:
  - name: id
    in: path
    required: true
    schema:
      type: string
      format: uuid
post:
  tags:
    - tasks
  summary: Pick an item from cell
  operationId: pickInstanceFromCell
  requestBody:
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            instanceId:
              type: string
              format: uuid
          required:
            - instanceId
  responses:
    "204":
      description: Successful operation
    "401":
      $ref: ../../components/responses/default-unauthorized.yaml
    "403":
      $ref: ../../components/responses/default-forbidden.yaml
    default:
      $ref: ../../components/responses/default-error.yaml
    "400":
      $ref: ../../components/responses/default-bad-request.yaml
