parameters:
  - name: id
    in: path
    required: true
    schema:
      type: string
      format: uuid
post:
  tags:
    - tasks
  summary: Mark task as completed
  operationId: markTaskAsCompleted
  responses:
    "201":
      description: Successful operation
    "401":
      $ref: ../../components/responses/default-unauthorized.yaml
    "403":
      $ref: ../../components/responses/default-forbidden.yaml
    default:
      $ref: ../../components/responses/default-error.yaml
    "400":
      $ref: ../../components/responses/default-bad-request.yaml
