// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// AssignRole implements assignRole operation.
//
// Assign Role to Employee.
//
// PATCH /employees/{id}/role-bindings
func (UnimplementedHandler) AssignRole(ctx context.Context, req *RoleBinding, params AssignRoleParams) error {
	return ht.ErrNotImplemented
}

// CreateCellGroup implements createCellGroup operation.
//
// Create Cell Group in Storage Space.
//
// POST /units/{unitId}/spaces/{spaceId}/groups
func (UnimplementedHandler) CreateCellGroup(ctx context.Context, req *StorageCellGroup, params CreateCellGroupParams) (r *StorageCellGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateCellKind implements createCellKind operation.
//
// Create Storage Cell Kind.
//
// POST /cell-kinds
func (UnimplementedHandler) CreateCellKind(ctx context.Context, req *StorageCellKind) (r *StorageCellKind, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateStorageCell implements createStorageCell operation.
//
// Create Storage Cell in Cell Group.
//
// POST /units/{unitId}/spaces/{spaceId}/groups/{groupId}/cells
func (UnimplementedHandler) CreateStorageCell(ctx context.Context, req *StorageCell, params CreateStorageCellParams) (r *StorageCell, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateStorageSpace implements createStorageSpace operation.
//
// Create Storage Space.
//
// POST /units/{unitId}/spaces
func (UnimplementedHandler) CreateStorageSpace(ctx context.Context, req *StorageSpace, params CreateStorageSpaceParams) (r *StorageSpace, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateSupplier implements createSupplier operation.
//
// Create Supplier.
//
// POST /suppliers
func (UnimplementedHandler) CreateSupplier(ctx context.Context, req *Supplier) (r *Supplier, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateUnit implements createUnit operation.
//
// Create Organization Unit.
//
// POST /units
func (UnimplementedHandler) CreateUnit(ctx context.Context, req *Unit) (r *Unit, _ error) {
	return r, ht.ErrNotImplemented
}

// DeleteCellGroup implements deleteCellGroup operation.
//
// Delete Cell Group.
//
// DELETE /units/{unitId}/spaces/{spaceId}/groups/{groupId}
func (UnimplementedHandler) DeleteCellGroup(ctx context.Context, params DeleteCellGroupParams) error {
	return ht.ErrNotImplemented
}

// DeleteCellKind implements deleteCellKind operation.
//
// Delete Storage Cell Kind.
//
// DELETE /cell-kinds/{id}
func (UnimplementedHandler) DeleteCellKind(ctx context.Context, params DeleteCellKindParams) error {
	return ht.ErrNotImplemented
}

// DeleteRoleBinding implements deleteRoleBinding operation.
//
// Delete Role Binding.
//
// DELETE /employees/{id}/role-bindings/{roleBindingId}
func (UnimplementedHandler) DeleteRoleBinding(ctx context.Context, params DeleteRoleBindingParams) error {
	return ht.ErrNotImplemented
}

// DeleteStorageCell implements deleteStorageCell operation.
//
// Delete Storage Cell.
//
// DELETE /units/{unitId}/spaces/{spaceId}/groups/{groupId}/cells/{cellId}
func (UnimplementedHandler) DeleteStorageCell(ctx context.Context, params DeleteStorageCellParams) error {
	return ht.ErrNotImplemented
}

// DeleteStorageSpace implements deleteStorageSpace operation.
//
// Delete Storage Space.
//
// DELETE /units/{unitId}/spaces/{spaceId}
func (UnimplementedHandler) DeleteStorageSpace(ctx context.Context, params DeleteStorageSpaceParams) error {
	return ht.ErrNotImplemented
}

// DeleteSupplier implements deleteSupplier operation.
//
// Delete Supplier.
//
// DELETE /suppliers/{id}
func (UnimplementedHandler) DeleteSupplier(ctx context.Context, params DeleteSupplierParams) error {
	return ht.ErrNotImplemented
}

// DeleteUnit implements deleteUnit operation.
//
// Delete Organization Unit.
//
// DELETE /units/{id}
func (UnimplementedHandler) DeleteUnit(ctx context.Context, params DeleteUnitParams) error {
	return ht.ErrNotImplemented
}

// GetCellGroupById implements getCellGroupById operation.
//
// Get Cell Group by ID with Cells.
//
// GET /units/{unitId}/spaces/{spaceId}/groups/{groupId}
func (UnimplementedHandler) GetCellGroupById(ctx context.Context, params GetCellGroupByIdParams) (r *GetCellGroupByIdOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCellGroups implements getCellGroups operation.
//
// Get list of Cell Groups in Storage Space.
//
// GET /units/{unitId}/spaces/{spaceId}/groups
func (UnimplementedHandler) GetCellGroups(ctx context.Context, params GetCellGroupsParams) (r []StorageCellGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCellKindById implements getCellKindById operation.
//
// Get Storage Cell Kind by ID.
//
// GET /cell-kinds/{id}
func (UnimplementedHandler) GetCellKindById(ctx context.Context, params GetCellKindByIdParams) (r *StorageCellKind, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCellKinds implements getCellKinds operation.
//
// Get list of Storage Cell Kinds.
//
// GET /cell-kinds
func (UnimplementedHandler) GetCellKinds(ctx context.Context) (r []StorageCellKind, _ error) {
	return r, ht.ErrNotImplemented
}

// GetCurrentEmployee implements getCurrentEmployee operation.
//
// Get current Employee.
//
// GET /me
func (UnimplementedHandler) GetCurrentEmployee(ctx context.Context) (r *GetCurrentEmployeeOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEmployeeById implements getEmployeeById operation.
//
// Get Employee by ID.
//
// GET /employees/{id}
func (UnimplementedHandler) GetEmployeeById(ctx context.Context, params GetEmployeeByIdParams) (r *GetEmployeeByIdOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetEmployees implements getEmployees operation.
//
// Get list of Employees in Organization.
//
// GET /employees
func (UnimplementedHandler) GetEmployees(ctx context.Context) (r []Employee, _ error) {
	return r, ht.ErrNotImplemented
}

// GetHealth implements getHealth operation.
//
// Get API health status.
//
// GET /health
func (UnimplementedHandler) GetHealth(ctx context.Context) (r GetHealthRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrderById implements getOrderById operation.
//
// Get Order by ID with Items.
//
// GET /orders/{id}
func (UnimplementedHandler) GetOrderById(ctx context.Context, params GetOrderByIdParams) (r GetOrderByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetOrders implements getOrders operation.
//
// Get list of Orders.
//
// GET /orders
func (UnimplementedHandler) GetOrders(ctx context.Context, params GetOrdersParams) (r GetOrdersRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRoleBindings implements getRoleBindings operation.
//
// Get list of Role Bindings for Employee.
//
// GET /employees/{id}/role-bindings
func (UnimplementedHandler) GetRoleBindings(ctx context.Context, params GetRoleBindingsParams) (r []RoleBinding, _ error) {
	return r, ht.ErrNotImplemented
}

// GetRoles implements getRoles operation.
//
// Get list of Roles.
//
// GET /rbac/roles
func (UnimplementedHandler) GetRoles(ctx context.Context) (r []Role, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpaceById implements getSpaceById operation.
//
// Get Storage Space by ID with Groups.
//
// GET /units/{unitId}/spaces/{spaceId}
func (UnimplementedHandler) GetSpaceById(ctx context.Context, params GetSpaceByIdParams) (r *GetSpaceByIdOK, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSpaces implements getSpaces operation.
//
// Get list of Storage Spaces in Unit.
//
// GET /units/{unitId}/spaces
func (UnimplementedHandler) GetSpaces(ctx context.Context, params GetSpacesParams) (r []StorageSpace, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStorageCellById implements getStorageCellById operation.
//
// Get Storage Cell by ID.
//
// GET /units/{unitId}/spaces/{spaceId}/groups/{groupId}/cells/{cellId}
func (UnimplementedHandler) GetStorageCellById(ctx context.Context, params GetStorageCellByIdParams) (r *StorageCell, _ error) {
	return r, ht.ErrNotImplemented
}

// GetStorageCells implements getStorageCells operation.
//
// Get list of Storage Cells in Cell Group.
//
// GET /units/{unitId}/spaces/{spaceId}/groups/{groupId}/cells
func (UnimplementedHandler) GetStorageCells(ctx context.Context, params GetStorageCellsParams) (r []StorageCell, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSupplierById implements getSupplierById operation.
//
// Get Supplier by ID.
//
// GET /suppliers/{id}
func (UnimplementedHandler) GetSupplierById(ctx context.Context, params GetSupplierByIdParams) (r *Supplier, _ error) {
	return r, ht.ErrNotImplemented
}

// GetSuppliers implements getSuppliers operation.
//
// Get list of Suppliers.
//
// GET /suppliers
func (UnimplementedHandler) GetSuppliers(ctx context.Context) (r []Supplier, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUnitById implements getUnitById operation.
//
// Get Unit by ID with Spaces.
//
// GET /units/{id}
func (UnimplementedHandler) GetUnitById(ctx context.Context, params GetUnitByIdParams) (r GetUnitByIdRes, _ error) {
	return r, ht.ErrNotImplemented
}

// GetUnits implements getUnits operation.
//
// Get list of Organization Units.
//
// GET /units
func (UnimplementedHandler) GetUnits(ctx context.Context, params GetUnitsParams) (r GetUnitsRes, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCellGroup implements updateCellGroup operation.
//
// Update Cell Group.
//
// PUT /units/{unitId}/spaces/{spaceId}/groups/{groupId}
func (UnimplementedHandler) UpdateCellGroup(ctx context.Context, req *StorageCellGroup, params UpdateCellGroupParams) (r *StorageCellGroup, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateCellKind implements updateCellKind operation.
//
// Update Storage Cell Kind.
//
// PUT /cell-kinds/{id}
func (UnimplementedHandler) UpdateCellKind(ctx context.Context, req *StorageCellKind, params UpdateCellKindParams) (r *StorageCellKind, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateStorageCell implements updateStorageCell operation.
//
// Update Storage Cell.
//
// PUT /units/{unitId}/spaces/{spaceId}/groups/{groupId}/cells/{cellId}
func (UnimplementedHandler) UpdateStorageCell(ctx context.Context, req *StorageCell, params UpdateStorageCellParams) (r *StorageCell, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateStorageSpace implements updateStorageSpace operation.
//
// Update Storage Space.
//
// PUT /units/{unitId}/spaces/{spaceId}
func (UnimplementedHandler) UpdateStorageSpace(ctx context.Context, req *StorageSpace, params UpdateStorageSpaceParams) (r *StorageSpace, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateSupplier implements updateSupplier operation.
//
// Update Supplier.
//
// PUT /suppliers/{id}
func (UnimplementedHandler) UpdateSupplier(ctx context.Context, req *Supplier, params UpdateSupplierParams) (r *Supplier, _ error) {
	return r, ht.ErrNotImplemented
}

// UpdateUnit implements updateUnit operation.
//
// Update Organization Unit.
//
// PUT /units/{id}
func (UnimplementedHandler) UpdateUnit(ctx context.Context, req *Unit, params UpdateUnitParams) (r *Unit, _ error) {
	return r, ht.ErrNotImplemented
}
