// Code generated by ogen, DO NOT EDIT.

package api

// OperationName is the ogen operation name
type OperationName = string

const (
	AssignRoleOperation         OperationName = "AssignRole"
	CreateCellGroupOperation    OperationName = "CreateCellGroup"
	CreateCellKindOperation     OperationName = "CreateCellKind"
	CreateStorageCellOperation  OperationName = "CreateStorageCell"
	CreateStorageSpaceOperation OperationName = "CreateStorageSpace"
	CreateSupplierOperation     OperationName = "CreateSupplier"
	CreateUnitOperation         OperationName = "CreateUnit"
	DeleteCellGroupOperation    OperationName = "DeleteCellGroup"
	DeleteCellKindOperation     OperationName = "DeleteCellKind"
	DeleteRoleBindingOperation  OperationName = "DeleteRoleBinding"
	DeleteStorageCellOperation  OperationName = "DeleteStorageCell"
	DeleteStorageSpaceOperation OperationName = "DeleteStorageSpace"
	DeleteSupplierOperation     OperationName = "DeleteSupplier"
	DeleteUnitOperation         OperationName = "DeleteUnit"
	GetCellGroupByIdOperation   OperationName = "GetCellGroupById"
	GetCellGroupsOperation      OperationName = "GetCellGroups"
	GetCellKindByIdOperation    OperationName = "GetCellKindById"
	GetCellKindsOperation       OperationName = "GetCellKinds"
	GetCurrentEmployeeOperation OperationName = "GetCurrentEmployee"
	GetEmployeeByIdOperation    OperationName = "GetEmployeeById"
	GetEmployeesOperation       OperationName = "GetEmployees"
	GetHealthOperation          OperationName = "GetHealth"
	GetOrderByIdOperation       OperationName = "GetOrderById"
	GetOrdersOperation          OperationName = "GetOrders"
	GetRoleBindingsOperation    OperationName = "GetRoleBindings"
	GetRolesOperation           OperationName = "GetRoles"
	GetSpaceByIdOperation       OperationName = "GetSpaceById"
	GetSpacesOperation          OperationName = "GetSpaces"
	GetStorageCellByIdOperation OperationName = "GetStorageCellById"
	GetStorageCellsOperation    OperationName = "GetStorageCells"
	GetSupplierByIdOperation    OperationName = "GetSupplierById"
	GetSuppliersOperation       OperationName = "GetSuppliers"
	GetUnitByIdOperation        OperationName = "GetUnitById"
	GetUnitsOperation           OperationName = "GetUnits"
	UpdateCellGroupOperation    OperationName = "UpdateCellGroup"
	UpdateCellKindOperation     OperationName = "UpdateCellKind"
	UpdateStorageCellOperation  OperationName = "UpdateStorageCell"
	UpdateStorageSpaceOperation OperationName = "UpdateStorageSpace"
	UpdateSupplierOperation     OperationName = "UpdateSupplier"
	UpdateUnitOperation         OperationName = "UpdateUnit"
)
