// Code generated by ogen, DO NOT EDIT.
package api

type GetHealthRes interface {
	getHealthRes()
}

type GetOrderByIdRes interface {
	getOrderByIdRes()
}

type GetOrdersRes interface {
	getOrdersRes()
}

type GetUnitByIdRes interface {
	getUnitByIdRes()
}

type GetUnitsRes interface {
	getUnitsRes()
}
